---
title: "Testing Git"
author: "Iqbal"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)

library(here)
```

```{r}
readxl::read_excel(
    "EVDataExplorer2025.xlsx"
) -> evdata
```

```{r}
read_csv(
   "owid-co2-data.csv"
) -> owd
```

```{r}
read.csv(
    "api-data.csv"
) -> apidata
```



```{r}
apidata %>%
  group_by(Country.Name, Country.Code, Indicator.Name, Indicator.Code) %>% 
  pivot_longer( 
    cols = 5:70, 
    names_to = "years", 
    values_to = "values") -> apidata.log

apidata.log %>% 
  mutate(
    years = stringr::str_remove_all(years, "X"),  
    years = as.integer(years)
  ) -> apidata.log



apidata.log %>% 
  ungroup() %>%
  select(-4) %>%
  group_by(Country.Name, Country.Code, years) %>%
  pivot_wider(
    names_from = Indicator.Name, 
    values_from = values
  ) -> apidata.clean


```


```{r}


owd %>%
  left_join(
    apidata.clean, 
    by = c(
      "country" = "Country.Name", 
      "year" = "years"
    )
  ) -> owd2

```


```{r}

evdata %>%
  left_join(
    owd2, by = c(
      "region_country" = "country", 
      "year" = "year"
    )
  ) -> evdata2


```

```{r}
read.csv(
    "popdata.csv"
) -> popdata
```


```{r}

popdata %>%
  select(-c(3, 4)) %>%
  group_by(
    Country.Name, Country.Code
    ) %>%
  pivot_longer(
    names_to = "year",
    values_to = "population",
    cols = 3:68
    ) -> popdata.long


popdata.long %>% 
  mutate(
    year = stringr::str_remove_all(
      year,
      "X"
      )
    ) -> popdata.long


```




```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
